// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/realtime_track_service.proto

// Package name

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeTrackService_GetRealtimeTrack_FullMethodName    = "/lrt_realtime_service.RealtimeTrackService/GetRealtimeTrack"
	RealtimeTrackService_StartPeriodicUpdate_FullMethodName = "/lrt_realtime_service.RealtimeTrackService/StartPeriodicUpdate"
)

// RealtimeTrackServiceClient is the client API for RealtimeTrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type RealtimeTrackServiceClient interface {
	GetRealtimeTrack(ctx context.Context, in *GeocodingRequest, opts ...grpc.CallOption) (*GeocodingResponse, error)
	StartPeriodicUpdate(ctx context.Context, in *GeocodingRequest, opts ...grpc.CallOption) (*GeocodingResponse, error)
}

type realtimeTrackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeTrackServiceClient(cc grpc.ClientConnInterface) RealtimeTrackServiceClient {
	return &realtimeTrackServiceClient{cc}
}

func (c *realtimeTrackServiceClient) GetRealtimeTrack(ctx context.Context, in *GeocodingRequest, opts ...grpc.CallOption) (*GeocodingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodingResponse)
	err := c.cc.Invoke(ctx, RealtimeTrackService_GetRealtimeTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeTrackServiceClient) StartPeriodicUpdate(ctx context.Context, in *GeocodingRequest, opts ...grpc.CallOption) (*GeocodingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodingResponse)
	err := c.cc.Invoke(ctx, RealtimeTrackService_StartPeriodicUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealtimeTrackServiceServer is the server API for RealtimeTrackService service.
// All implementations must embed UnimplementedRealtimeTrackServiceServer
// for forward compatibility.
//
// Service definition
type RealtimeTrackServiceServer interface {
	GetRealtimeTrack(context.Context, *GeocodingRequest) (*GeocodingResponse, error)
	StartPeriodicUpdate(context.Context, *GeocodingRequest) (*GeocodingResponse, error)
	mustEmbedUnimplementedRealtimeTrackServiceServer()
}

// UnimplementedRealtimeTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeTrackServiceServer struct{}

func (UnimplementedRealtimeTrackServiceServer) GetRealtimeTrack(context.Context, *GeocodingRequest) (*GeocodingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealtimeTrack not implemented")
}
func (UnimplementedRealtimeTrackServiceServer) StartPeriodicUpdate(context.Context, *GeocodingRequest) (*GeocodingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPeriodicUpdate not implemented")
}
func (UnimplementedRealtimeTrackServiceServer) mustEmbedUnimplementedRealtimeTrackServiceServer() {}
func (UnimplementedRealtimeTrackServiceServer) testEmbeddedByValue()                              {}

// UnsafeRealtimeTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeTrackServiceServer will
// result in compilation errors.
type UnsafeRealtimeTrackServiceServer interface {
	mustEmbedUnimplementedRealtimeTrackServiceServer()
}

func RegisterRealtimeTrackServiceServer(s grpc.ServiceRegistrar, srv RealtimeTrackServiceServer) {
	// If the following call pancis, it indicates UnimplementedRealtimeTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeTrackService_ServiceDesc, srv)
}

func _RealtimeTrackService_GetRealtimeTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeTrackServiceServer).GetRealtimeTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeTrackService_GetRealtimeTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeTrackServiceServer).GetRealtimeTrack(ctx, req.(*GeocodingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeTrackService_StartPeriodicUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeTrackServiceServer).StartPeriodicUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeTrackService_StartPeriodicUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeTrackServiceServer).StartPeriodicUpdate(ctx, req.(*GeocodingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RealtimeTrackService_ServiceDesc is the grpc.ServiceDesc for RealtimeTrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeTrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lrt_realtime_service.RealtimeTrackService",
	HandlerType: (*RealtimeTrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRealtimeTrack",
			Handler:    _RealtimeTrackService_GetRealtimeTrack_Handler,
		},
		{
			MethodName: "StartPeriodicUpdate",
			Handler:    _RealtimeTrackService_StartPeriodicUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/realtime_track_service.proto",
}
